exclude: 'venv-update'
repos:
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
        exclude: \.(css|ts|tsx|bck|csv)$
    -   id: check-merge-conflict
    -   id: check-json
    -   id: debug-statements
    -   id: check-added-large-files
        args: [--maxkb=500]
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: check-yaml
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.5.0
    hooks:
      - id: reorder-python-imports
        name: reorder python imports
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.942"
    hooks:
    -   id: mypy